-- Insert sample CNC machines for hourly QC workflow
INSERT INTO public.machines (machine_id, name, department_id, status, location) VALUES
('CNC-001', 'DMG MORI CMX 50 U', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - A1'),
('CNC-002', 'Haas VF-3', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - A2'),
('CNC-003', 'Mazak INTEGREX i-100', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - A3'),
('CNC-004', 'Okuma LU-300MY', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - A4'),
('CNC-005', 'DMG MORI NLX 2500', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - A5'),
('CNC-006', 'Haas ST-10Y', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - B1'),
('CNC-007', 'Mazak QTN 250-II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - B2'),
('CNC-008', 'Okuma GENOS L250-E', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - B3'),
('CNC-009', 'DMG MORI CTX beta 800', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - B4'),
('CNC-010', 'Haas VF-2SS', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - B5'),
('CNC-011', 'Mazak VARIAXIS i-300', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - C1'),
('CNC-012', 'Okuma MA-500HII', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - C2'),
('CNC-013', 'DMG MORI CMX 600 V', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - C3'),
('CNC-014', 'Haas UMC-750', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - C4'),
('CNC-015', 'Mazak INTEGREX e-1850V', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - C5'),
('CNC-016', 'Okuma LU-35 II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - D1'),
('CNC-017', 'DMG MORI NHX 4000', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - D2'),
('CNC-018', 'Haas ST-20Y', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - D3'),
('CNC-019', 'Mazak QTN 200-II MSY', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - D4'),
('CNC-020', 'Okuma GENOS M460-V', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - D5');

-- Add more machines to reach 50 total
INSERT INTO public.machines (machine_id, name, department_id, status, location) VALUES
('CNC-021', 'DMG MORI DMU 50', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - E1'),
('CNC-022', 'Haas VF-4SS', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - E2'),
('CNC-023', 'Mazak NEXUS 250-II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - E3'),
('CNC-024', 'Okuma MB-4000H', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - E4'),
('CNC-025', 'DMG MORI NTX 1000', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - E5'),
('CNC-026', 'Haas ST-30Y', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - F1'),
('CNC-027', 'Mazak QTN 350-II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - F2'),
('CNC-028', 'Okuma LU-300M', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - F3'),
('CNC-029', 'DMG MORI CTX gamma 1250', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - F4'),
('CNC-030', 'Haas VF-6/50', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - F5'),
('CNC-031', 'Mazak VARIAXIS i-500', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - G1'),
('CNC-032', 'Okuma MA-600HII', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - G2'),
('CNC-033', 'DMG MORI CMX 800 V', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - G3'),
('CNC-034', 'Haas UMC-1000', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - G4'),
('CNC-035', 'Mazak INTEGREX e-2000V', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - G5'),
('CNC-036', 'Okuma LU-45 II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - H1'),
('CNC-037', 'DMG MORI NHX 5000', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - H2'),
('CNC-038', 'Haas ST-40Y', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - H3'),
('CNC-039', 'Mazak QTN 450-II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - H4'),
('CNC-040', 'Okuma GENOS M560-V', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - H5'),
('CNC-041', 'DMG MORI DMU 75', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - I1'),
('CNC-042', 'Haas VF-8/50', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - I2'),
('CNC-043', 'Mazak NEXUS 410A-II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - I3'),
('CNC-044', 'Okuma MB-5000H', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - I4'),
('CNC-045', 'DMG MORI NTX 2000', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - I5'),
('CNC-046', 'Haas ST-55Y', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - J1'),
('CNC-047', 'Mazak QTN 550-II', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - J2'),
('CNC-048', 'Okuma LU-400M', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - J3'),
('CNC-049', 'DMG MORI CTX delta 1250', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - J4'),
('CNC-050', 'Haas VF-12/50', (SELECT id FROM public.departments WHERE name = 'Production' LIMIT 1), 'available', 'Production Floor - J5');