-- Update the auto_generate_work_order_from_line_item function to not set display_id
-- The wo_number will be auto-generated by the trigger in WO-YYYY-XXXXX format
CREATE OR REPLACE FUNCTION public.auto_generate_work_order_from_line_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  new_wo_uuid uuid;
  so_record record;
  generated_wo_number text;
BEGIN
  IF (TG_OP = 'UPDATE' AND OLD.status != 'approved' AND NEW.status = 'approved' AND NEW.work_order_id IS NULL) THEN
    SELECT * INTO so_record FROM sales_orders WHERE id = NEW.sales_order_id;

    -- wo_number is auto-generated by trigger, do not set display_id or wo_number here
    INSERT INTO work_orders (
      customer,
      customer_id,
      customer_po,
      item_code,
      quantity,
      due_date,
      sales_order,
      so_id,
      status,
      current_stage,
      gross_weight_per_pc,
      net_weight_per_pc,
      material_size_mm,
      cycle_time_seconds,
      financial_snapshot
    ) VALUES (
      so_record.customer,
      so_record.customer_id,
      so_record.po_number,
      NEW.item_code,
      NEW.quantity,
      NEW.due_date,
      so_record.so_id,
      NEW.sales_order_id,
      'pending',
      'goods_in',
      NEW.gross_weight_per_pc_grams,
      NEW.net_weight_per_pc_grams,
      NEW.material_size_mm,
      NEW.cycle_time_seconds,
      jsonb_build_object(
        'currency', so_record.currency,
        'payment_terms_days', so_record.payment_terms_days,
        'incoterm', so_record.incoterm,
        'so_total', so_record.total_amount,
        'line_item', jsonb_build_object(
          'item_code', NEW.item_code,
          'quantity', NEW.quantity,
          'price_per_pc', NULL,
          'line_amount', NULL,
          'due_date', NEW.due_date,
          'drawing_number', NULL,
          'alloy', NEW.alloy,
          'material_size_mm', NEW.material_size_mm
        )
      )
    ) RETURNING id, wo_number INTO new_wo_uuid, generated_wo_number;

    UPDATE sales_order_line_items
    SET work_order_id = new_wo_uuid
    WHERE id = NEW.id;

    RAISE NOTICE 'Generated Work Order % for line item % of SO %', generated_wo_number, NEW.line_number, so_record.so_id;
  END IF;
  RETURN NEW;
END;
$$;